---
- hosts: all
  become: yes

  tasks:
    - name: Update package repository
      apt:
        update_cache: yes

    - name: Install system dependencies
      apt:
        name:
          - python3
          - python3-pip
          - redis-server
        state: present

    - name: Install Python dependencies
      pip:
        name:
          - flask
          - redis

    - name: Start Redis server
      service:
        name: redis-server
        state: started
        enabled: yes

    - name: Copy application files
      synchronize:
        src: /vagrant/
        dest: /var/www/flask-app/
        delete: yes

    - name: Run Flask app
      shell: |
        cd /var/www/flask-app
        nohup python3 app.py > /dev/null 2>&1 &
