- hosts: all
  become: true

  tasks:
    # Update apt packages
    - name: Update apt packages
      apt:
        update_cache: yes

    # Install Python 3 and pip (this may no longer be necessary if we're using Docker)
    - name: Install Python 3 and pip3
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: present
     

    # Install Redis
    - name: Install Redis
      apt:
        name: redis-server
        state: present

    - name: Ensure Redis is started
      service:
        name: redis-server
        state: started
        enabled: yes


    

    # Install Docker
    - name: Install Docker
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Python dependencies
      pip:
        requirements: /vagrant/dependances.txt
        executable: /usr/bin/pip3

 
