Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.network "private_network", ip: "192.168.56.10"
    config.vm.synced_folder ".", "/vagrant"  # Sync current directory to VM
    config.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yml"
    end
end
